### ISSUE TITLE
チェックボックス型のリストフィールドで文字列の途中で改行してしまう

### ISSUE THREAD

**Issue by amidaku** [farend/redmine_theme_farend_bleuclair#1]
チェックボックスタイプのリスト型カスタムフィールドをチケットに割り当てると、チケット編集画面で当該のフィールドの項目文字列が途中で改行してしまいます。
![2017-02-03 18 34 22](https://cloud.githubusercontent.com/assets/772004/22586326/72a8cd1e-ea3f-11e6-9d1b-0213f18c0b72.png)

**Comment by ishikawa999** [comment]
Redmine4.0で動かしたところ、再現できませんでした。

**Comment by ishikawa999** [comment]
845c2da4acc91966b677f0aa0d2cdf016e5410ef
で対応しました。
