### ISSUE TITLE
Group name overlaps the group icon in Members tab

### ISSUE THREAD

**Issue by vividtone** [farend/redmine_theme_farend_bleuclair#11]
Please see the screenshot below. The group name "A Team" and "B Team" overlap the group icon. I tested with 4.0.5.devel.19362.

![image](https://user-images.githubusercontent.com/114863/70670153-9efc0500-1cbb-11ea-8706-1c847343ea02.png)

**Comment by ishikawa999** [comment]
I fixed this bug.
