### ISSUE TITLE
Redmine 4.1.0. でチケットのページで「作業時間」、「関係しているリビジョン」で表示が崩れる

### ISSUE THREAD

**Issue by TomonoriMatsumura** [farend/redmine_theme_farend_bleuclair#13]
### Redmine環境

- CentOS7
- Redmine 4.1.0.stable.19408
- Ruby version 2.5.3-p105 (2018-10-18) [x86_64-linux]
- Rails version 5.2.4.1
-  Git 1.8.3.1
- Redmine plugins
なし

### ブラウザ
- MacOS 10.14.5
 - Safari バージョン12.1.1 (14607.2.6.1.1) 

### bleuclairのバージョン

commit 6fa2dcf25a8f4194f1f42bab670a30fb765838ec

<img width="1439" alt="スクリーンショット 2020-01-08 22 51 52" src="https://user-images.githubusercontent.com/1615430/71983201-9b7f7d80-3269-11ea-950c-84bf58c2c8bd.png">

### 症状

チケットのページで「作業時間」、「関係しているリビジョン」で表示が崩れる

<img width="1440" alt="スクリーンショット 2020-01-08 22 48 16" src="https://user-images.githubusercontent.com/1615430/71982955-11cfb000-3269-11ea-8a69-f92e0c68caa5.png">
<img width="1440" alt="スクリーンショット 2020-01-08 22 47 50" src="https://user-images.githubusercontent.com/1615430/71982971-1a27eb00-3269-11ea-9b1b-2df43014648a.png">

**Comment by ishikawa999** [comment]
@TomonoriMatsumura 
フィードバックをいただきありがとうございます！

Redmine4.0 と Redmine4.1では大きくHTMLの構造が違うため、現在bleuclairはブランチを分けてそれぞれのバージョンに対応しています。

Redmine4.1用のテーマは redmine4.1ブランチで開発を行っていますので、そちらのブランチのテーマをご利用いただければご報告いただいた問題は解決すると思います。
(利用されているbleuclairのバージョンが 6fa2dcf というところから見て、現在は恐らくmasterブランチのテーマを利用されていると思います)  

Redmine4.1用のテーマを利用する方法: https://github.com/farend/redmine_theme_farend_bleuclair#1-テーマが格納されたディレクトリを作成 (の3つ目)

以上、よろしくお願いいたします

**Comment by TomonoriMatsumura** [comment]
表示確認しました。

正常に表示されるようになりました。

<img width="1440" alt="スクリーンショット 2020-01-29 22 17 52" src="https://user-images.githubusercontent.com/1615430/73359928-41f8f480-42e5-11ea-8aa7-9a4e64e1c9ea.png">
<img width="1440" alt="スクリーンショット 2020-01-29 22 17 47" src="https://user-images.githubusercontent.com/1615430/73359930-41f8f480-42e5-11ea-9a63-dac4bbe5eb4c.png">

**Comment by ishikawa999** [comment]
@TomonoriMatsumura 

早速ご確認いただきありがとうございました。

インストール方法がREADMEで強調できていなかったため、下の画像のように注意書きを追加しました。
<img width="945" alt="ScreenShot-2020-02-04-11 09 12" src="https://user-images.githubusercontent.com/14245262/73707431-e7292800-473e-11ea-804a-9fd15a39558e.png">

このIssueはこれでCloseといたします。
