### ISSUE TITLE
[RFE]フォーラムのメッセージ表示をチケットの履歴と同様の吹き出しに

### ISSUE THREAD

**Issue by torutk** [farend/redmine_theme_farend_bleuclair#19]
フォーラムのメッセージ表示画面において、各メッセージの返答ヘッダー部分を
チケットの履歴と同様の吹き出し表示としていただけるよう機能追加の要望です。
ご検討いただければ幸いです。

**Comment by ishikawa999** [comment]
ご要望をいただきありがとうございます。

これについては本来チケットの履歴と同じようにすべきところを実装漏れしていたので、対応します。

**Comment by ishikawa999** [comment]
各バージョンのブランチに変更を追加しました。

**Comment by torutk** [comment]
redmine4.1ブランチで反映確認しました。よい感じです。
ありがとうございます。
