### ISSUE TITLE
remine4.1.1でガントチャートが表示されない。

### ISSUE THREAD

**Issue by blacknights** [farend/redmine_theme_farend_bleuclair#20]
redmine4.1.1に、remine4.1対応版をいれましたが、ガントチャートが一瞬表示されて消えます。
左のチケット部分は表示されていますが、線表部分は見えません。
もちろん、テーマをデフォルトに戻すと、正常に表示されます。

**Comment by ishikawa999** [comment]
@blacknights 

問題を共有していただきありがとうございます。
手元でRedmine4.1.1を動かしredmine4.1用のテーマを入れてみたのですが、問題を再現できませんでした。

おそらく何か異なる点があると思いますので、以下の点について共有できる範囲で教えていただけないでしょうか？
* 入れているプラグイン
* View Customizeプラグインを利用されている場合、ガントチャートのページに対して適用しているカスタマイズがないか
* ブラウザ

よろしくお願いいたします 🙇‍♀️

**Comment by blacknights** [comment]
@ishikawa999 
Shift+F5で更新したら、正常に表示できるようになりました。
redmineの古い環境と合わせて、新環境を検証していたせいで、古いキャッシュが影響したようです。

お騒がせました。
