### ISSUE TITLE
Cyrillic font breaks

### ISSUE THREAD

**Issue by andreyddk** [farend/redmine_theme_farend_bleuclair#28]
Hi!
I have a problem in iphone 6/7 with cyrillic font 
Its possible fixed?

https://ibb.co/CnhmNwT

**Comment by ishikawa999** [comment]
@andreyddk 

Thank you for using the theme.
I checked the screenshot, but I couldn't figure out what was wrong with the theme because I couldn't read Cyrillic.

Would you please explain the problem in the text?

**Comment by andreyddk** [comment]
> I couldn't read Cyrillic
Sorry about this)

For example I check in android device, and spaces between words have a normal size.
https://ibb.co/dL0HZX1

But in ios something wrong.
https://ibb.co/7475qd4
https://ibb.co/CnhmNwT

**Comment by ishikawa999** [comment]
@andreyddk 

> > I couldn't read Cyrillic
> > Sorry about this)
> 
> For example I check in android device, and spaces between words have a normal size.
> https://ibb.co/dL0HZX1
> 
> But in ios something wrong.
> https://ibb.co/7475qd4
> https://ibb.co/CnhmNwT

Thank you for providing detailed information.
I think it's probably the same problem as the story written in https://stackoverflow.com/a/26001424.

https://stackoverflow.com/a/26001424

> According to https://hsivonen.fi/hiragino/ (my emphasis added), "Mac OS X comes with new a family of high-quality Japanese fonts called Hiragino. The fonts also contain high-quality glyphs for the Western European subset of the Latin script. The glyphs for basic Greek and the Russian subset of the Cyrillic script look fine in isolation but are kerned to match the width of Kanji blocks. This makes the fonts ill-suited for Greek or Russian text."

This theme was created with the idea of ​​using it in Japanese, so I use the hiragino font. Probably it is displayed in that font when using the iPhone.

**Comment by ishikawa999** [comment]
@andreyddk 

After downloading this theme, open `bleuclair/stylesheets/application.css` with an editor and remove "Hiragino Kaku Gothic Pro" and "Hiragino Sans", which will probably solve the problem.

Example: https://github.com/farend/redmine_theme_farend_bleuclair/blob/redmine4.0/stylesheets/application.css#L3

I don't want to change this hiragino font as it is very easy to use in Japanese.
Is it possible to manually rewrite the code as I wrote above?

**Comment by andreyddk** [comment]
I am replace font to "Open Sans"
https://ibb.co/xgW9JJd

Looks better) Thank you for explaining)

**Comment by ishikawa999** [comment]
@andreyddk 

Thank you for checking immediately.
I'll keep the issue open until the Bleuclair theme resolves this issue or decides not to support it.

**Comment by ishikawa999** [comment]
I'll keep the issue open until the Bleuclair theme resolves this issue or decides not to support it.

**Comment by ishikawa999** [comment]
The Bleuclair theme for Redmine 4.2 has been modified to prevent this problem. 
79425b9
