### ISSUE TITLE
Hide sidebar when print a page using a web browser

### ISSUE THREAD

**Issue by vividtone** [farend/redmine_theme_farend_bleuclair#32]
Default theme:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/114863/107181384-13484a80-6a1e-11eb-9119-fa0a9e5accca.png">

Bleuclair theme:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/114863/107181467-3ffc6200-6a1e-11eb-9442-af015a851eca.png">

**Comment by ishikawa999** [comment]
Thank you for reporting the issue.
Add a hide-when-print class to the sidebar like https://www.redmine.org/issues/29791.

**Comment by ishikawa999** [comment]
93a7143f316a3dd20c561b63a87e4d18b16d135d commit fixed the issue.
