### ISSUE TITLE
Issues not in the tree are also collapsed when collapsing a tree in gantt

### ISSUE THREAD

**Issue by vividtone** [farend/redmine_theme_farend_bleuclair#43]
See the screenshots below. Issue 15 and 18 are root-level issues. However, if you collapse the tree grows from issue 15, not only descendant of issue 15 but also an independent issue 18 is also collapsed as if it is a descendant of issue 15.

![image](https://user-images.githubusercontent.com/114863/127966775-e5b37b1b-e9f3-4a28-9292-3cfb33f8157b.png)

![image](https://user-images.githubusercontent.com/114863/127966855-f21c8bcf-f5cc-4f07-8104-725a6c105de8.png)

I think that is not a bug of Redmine but Bleuclair theme because the problem does not occur when using any of the built-in themes in Redmine.

![image](https://user-images.githubusercontent.com/114863/127968634-f9b01a0b-2e48-49a3-9906-e4703b282834.png)

**Comment by ishikawa999** [comment]
Fix: https://github.com/farend/redmine_theme_farend_bleuclair/commit/951511640c3bd0f942bf3ce0c52f4cda4ea89ac9
