### ISSUE TITLE
Cite, Edit, Remove and permalink icons / links missing 

### ISSUE THREAD

**Issue by MagicFab** [farend/redmine_theme_farend_bleuclair#45]
When looking at a ticket, each comment in it normally has Cite, Edit, Remove and permalink icons / links.

These are missing in this theme.

![image](https://user-images.githubusercontent.com/317514/133481307-0e7d60d5-222e-4965-b1c9-4db19212ea7b.png)

**Comment by ishikawa999** [comment]
@MagicFab 

Please tell me the next version to investigate the problem:
* Redmine version (example: 4.0.9)
* Bleuclair branch name or git latest commit hash
  * How to find it: `cd /your/path/redmine/public/bleuclair; git branch --contains; git rev-parse HEAD;`

As described in section https://github.com/farend/redmine_theme_farend_bleuclair#install, you need to change the installation method depending on the version of Redmine.
If your Redmine version does not match your Bleuclair branch, it may not show up properly.

**Comment by MagicFab** [comment]
Thank you, the theme version we had was outdated on this particular host. Removing the theme and reinstalling using instructions for 4.0 solved the issue.
