### ISSUE TITLE
Fold-out folder on DMSF screen hide fold-in arrow

### ISSUE THREAD

**Issue by fhaefemeier** [farend/redmine_theme_farend_bleuclair#51]
## System

Redmine: 4.2.5
Plugin: [DMSF](https://github.com/farend/redmine_theme_farend_bleuclair)

## Issue

I use the DMSF plugin to organize my attached documents in redmine. If I enable the theme "farend_bleuclair" (which I really like), the screen which gives an overview over the projects / files has a minor issue. If I fold-out a project, the fold-in arrow disappear. It does not happen in the standard theme.

* Screenshot with standrad theme
<img width="259" alt="Screenshot-DMSF-Standard" src="https://user-images.githubusercontent.com/17227813/163602793-ad6d3757-c2f6-47cf-820d-b9ae4918c846.png">
* Screenshot with your theme
<img width="400" alt="Screenshot-DMSF-Bleuclair" src="https://user-images.githubusercontent.com/17227813/163602825-fd17f5aa-49a9-4e17-9d5a-544f06b92c74.png">

**Comment by ishikawa999** [comment]
@fhaefemeier 

Thanks for reporting the issue.
I changed 8e5314e98fcc003cd2985a1af2e68be96f2a4f64 fixes the problem.
Could you confirm that the latest code in the master or redmine4.2 branch cures the problem?

**Comment by fhaefemeier** [comment]
Thanks @ishikawa999, works like a charm. Perfect!

**Comment by ishikawa999** [comment]
> Thanks @ishikawa999, works like a charm. Perfect!

Thank you for your review.
I will close the issue.
