### ISSUE TITLE
Version 5.0

### ISSUE THREAD

**Issue by formigadiablo** [farend/redmine_theme_farend_bleuclair#61]
Can this be used for Redmine 5.0?

**Comment by ishikawa999** [comment]
@formigadiablo 
It is available. I am using Redmine 5.0.4 and Bleuclair and have not found problems so far.

**Comment by formigadiablo** [comment]
Okey thanks! And could you give me some quick guide on how to install it? I have just installed plugins and I am losing a bit looking at the guide in the code page...

**Comment by formigadiablo** [comment]
Thanks!
