### ISSUE TITLE
README suggests an outdated branch for Redmine 4.2 or later

### ISSUE THREAD

**Issue by tevino** [farend/redmine_theme_farend_bleuclair#78]
As a newcomer, the README suggests me to:

`git clone -b redmine4.2  https://github.com/farend/redmine_theme_farend_bleuclair.git public/themes/bleuclair`

However the latest commit of the `redmine4.2` branch was over a year ago, what I really need is:

`git clone https://github.com/farend/redmine_theme_farend_bleuclair.git public/themes/bleuclair`

Is this the correct way to install this theme?

**Comment by tevino** [comment]
BTW, the theme looks 💯 fantastic, thank you for the work! 😃

**Comment by ishikawa999** [comment]
@tevino 
> As a newcomer, the README suggests me to:
> 
> `git clone -b redmine4.2 https://github.com/farend/redmine_theme_farend_bleuclair.git public/themes/bleuclair`
> 
> However the latest commit of the `redmine4.2` branch was over a year ago, what I really need is:
> 
> `git clone https://github.com/farend/redmine_theme_farend_bleuclair.git public/themes/bleuclair`
> 
> Is this the correct way to install this theme?

Thank you for your feedback. I'm glad to hear that you are using our theme.

The reason we have different downloads for each version of Redmine with the Bleuclair theme is that the HTML structure can vary depending on the version of Redmine, and the same CSS or JavaScript might not work properly. However, as you pointed out, we haven't been managing the versions with tags as we should have recently. I am planning to create a new tag for 5.0 and update the README accordingly.

**Comment by ishikawa999** [comment]
@tevino 

https://github.com/farend/redmine_theme_farend_bleuclair?tab=readme-ov-file#1-create-a-directory-containing-themes
Updated README.
