### ISSUE TITLE
リポジトリブラウザと連携させた時に表示が崩れる

### ISSUE THREAD

**Issue by TomonoriMatsumura** [farend/redmine_theme_farend_bleuclair#8]
### Redmine環境

- CentOS7
- Redmine version 4.0.4.stable.18538
- Ruby version 2.5.3-p105 (2018-10-18) [x86_64-linux]
- Rails version 5.2.3
 -  Git 1.8.3.1
 - Redmine plugins
なし

### ブラウザ
- MacOS 10.14.5
 - Safari バージョン12.1.1 (14607.2.6.1.1) 

### 利用したコマンド

`git clone -b redmine4.0 https://github.com/farend/redmine_theme_farend_bleuclair.git public/themes/bleuclair`

リポジトリブラウザと連携させると表示が崩れる

<img width="1440" alt="スクリーンショット 2019-09-26 17 23 32" src="https://user-images.githubusercontent.com/1615430/65671986-3b324a80-e083-11e9-9b30-0df2f6141f3d.png">

拡大表示だと問題ない

<img width="1440" alt="スクリーンショット 2019-09-26 17 24 14" src="https://user-images.githubusercontent.com/1615430/65671998-3ff6fe80-e083-11e9-8fe1-f5ef0c95cc96.png">

**Comment by ishikawa999** [comment]
@TomonoriMatsumura 

問題を共有していただきありがとうございます。
リポジトリありの環境での動作確認が不十分だったせいでご迷惑をおかけしました。

Redmine4.0用で下のスクリーンショットのような見た目になるように変更を加えました。
(3.4用についても同様に変更を加えます)
![image](https://user-images.githubusercontent.com/14245262/65733448-c8b87d80-e109-11e9-9643-3e171a9a4968.png)

![image](https://user-images.githubusercontent.com/14245262/65733436-bcccbb80-e109-11e9-93dc-4edcaeb76fc9.png)

**Comment by TomonoriMatsumura** [comment]
動作確認出来ました

<img width="1440" alt="スクリーンショット 2019-09-27 13 42 10" src="https://user-images.githubusercontent.com/1615430/65742805-b6037000-e12c-11e9-9aa9-9058a5f171e1.png">

**Comment by ishikawa999** [comment]
@TomonoriMatsumura 
ご確認いただきありがとうございました！
一時的な対応ですので、今後見た目の方は改善していきたいと考えています。
