### ISSUE TITLE
Fix Bleuclair not working in latest Redmine (support propshaft)

### ISSUE THREAD

**Issue by ishikawa999** [farend/redmine_theme_farend_bleuclair#81]
Related: https://www.redmine.org/issues/39111

**Comment by ishikawa999** [comment]
Perhaps the paths that are written relative to the following are not working properly because of the change of directory
https://github.com/farend/redmine_theme_farend_bleuclair/blob/6a4a1ff624a51992a67641ad33e6d5a561fe0501/stylesheets/application.css#L1-L2

**Comment by ishikawa999** [comment]
https://github.com/farend/redmine_theme_farend_bleuclair/tree/support-propshaft

**Comment by vividtone** [comment]
The change c06330c causes a problem if the application is deployed under a subdirectory such as `http://www.example.com/redmine`.

I think it should be fixed like this:

```diff
diff --git a/themes/bleuclair/stylesheets/application.css b/themes/bleuclair/stylesheets/application.css
index d52e6a447..a7616b249 100644
--- a/themes/bleuclair/stylesheets/application.css
+++ b/themes/bleuclair/stylesheets/application.css
@@ -1,2 +1,2 @@
-@import url(/application.css);
+@import url(../../application.css);
 @import url(./theme.css);
```

**Comment by ishikawa999** [comment]
@vividtone 

Thank you for your feedback.
I have found the countermeasure to be effective and have added commit f9246941aa99142ea42949f8b44e07688f1dfdb5

**Comment by ishikawa999** [comment]
The changes introduced in [Redmine Revision 23173](https://www.redmine.org/projects/redmine/repository/svn/revisions/23173) have eliminated the need for modifications on the theme side.
